# 5 | K Nearest Neighbours Classification

## Importing libraries 

In [1]:
import pandas as pd                                                 #data manipulation
import numpy as np                                                  #data manipulation
import sklearn                                                      #ML support
from sklearn.neighbors import KNeighborsClassifier as knn           #KNN classifier

In [2]:
df=pd.read_csv("KNN.csv")                                           #loading data into data frame
df

X  Y Class
0  2  4     N
1  4  6     N
2  4  4     P
3  4  2     N
4  6  4     N
5  6  2     P

In [3]:
x=df.iloc[:,:-1].values
y=df.iloc[:,2].values

In [4]:
x

array([[2, 4],
       [4, 6],
       [4, 4],
       [4, 2],
       [6, 4],
       [6, 2]], dtype=int64)

In [5]:
y

array(['N', 'N', 'P', 'N', 'N', 'P'], dtype=object)

## Classification model creation and training

In [6]:
classifier=knn(n_neighbors=3)                                       #creating a knn model

In [7]:
classifier.fit(x,y)                                                 #training the data

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [8]:
x_test=np.array([6,6])
y_predict=classifier.predict([x_test])                              #prediction using model

In [9]:
y_predict

array(['N'], dtype=object)

In [10]:
x_test=np.array([4,2])

In [11]:
classifier=knn(n_neighbors=3, weights='distance')                   #weighted classification
classifier.fit(x,y)
y_predict=classifier.predict([x_test])

In [12]:
y_predict

array(['N'], dtype=object)

In [13]:
x_test=np.array([4.2,3.8])
y_predict=classifier.predict([x_test])
y_predict

array(['P'], dtype=object)

## As k increases accuracy decreases

In [14]:
df=pd.read_csv("KNN1.csv")

In [15]:
df

Height  Age  Weight
0    5.00   45      77
1    5.11   26      47
2    5.60   30      55
3    5.90   34      59
4    4.80   40      72
5    5.80   36      60
6    5.30   19      40
7    5.80   28      60
8    5.50   23      45
9    5.60   32      58

In [16]:
x=df.iloc[:,:-1].values
y=df.iloc[:,2].values

In [17]:
x

array([[ 5.  , 45.  ],
       [ 5.11, 26.  ],
       [ 5.6 , 30.  ],
       [ 5.9 , 34.  ],
       [ 4.8 , 40.  ],
       [ 5.8 , 36.  ],
       [ 5.3 , 19.  ],
       [ 5.8 , 28.  ],
       [ 5.5 , 23.  ],
       [ 5.6 , 32.  ]])

In [18]:
y

array([77, 47, 55, 59, 72, 60, 40, 60, 45, 58], dtype=int64)

In [19]:
classifier=knn(n_neighbors=3)

In [20]:
classifier.fit(x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [21]:
x_test=np.array([5.5,26])
y_predict=classifier.predict([x_test])

In [22]:
y_predict

array([45], dtype=int64)

In [23]:
classifier=knn(n_neighbors=4)

In [24]:
classifier.fit(x,y)
x_test=np.array([5.5,26])
y_predict=classifier.predict([x_test])
y_predict

array([45], dtype=int64)

In [25]:
classifier=knn(n_neighbors=9)
classifier.fit(x,y)
x_test=np.array([5.5,26])
y_predict=classifier.predict([x_test])
y_predict

array([60], dtype=int64)

In [26]:
classifier=knn(n_neighbors=1)
classifier.fit(x,y)
x_test=np.array([5.5,26])
y_predict=classifier.predict([x_test])
y_predict

array([47], dtype=int64)