# 2 | Feature extraction, selection & Dimentionality Reduction 

1. Variance Threshold
2. PCA
3. Dict vectorizer
4. Count vectorizer
5. Tfidf vectorizer

## Importing Libraries

In [1]:
import numpy as np                                                   #data manipulation
import pandas as pd                                                  #data manipulation
from sklearn.datasets import load_boston                             #dataset
from sklearn.feature_selection import VarianceThreshold              #feature Selection
from sklearn import datasets                                         #existing datasets in sklearn
from sklearn.decomposition import PCA                                #PCA
from sklearn.model_selection import train_test_split                 #splitting training & testing data
from sklearn.feature_extraction import DictVectorizer                #feature extraction
from sklearn.feature_extraction.text import CountVectorizer          #feature extraction
from sklearn.feature_extraction.text import TfidfVectorizer          #feature extraction

## Loading Boston dataset

In [2]:
boston=load_boston()
X=boston.data                                                        #features
Y=boston.target                                                      #class label

In [3]:
X.shape                                                              #rows,columns

(506, 13)

In [4]:
Y.shape                                                              #single column

(506,)

## Feature Selection

In [5]:
X[0:3,:]

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, 0.0000e+00, 5.3800e-01,
        6.5750e+00, 6.5200e+01, 4.0900e+00, 1.0000e+00, 2.9600e+02,
        1.5300e+01, 3.9690e+02, 4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        6.4210e+00, 7.8900e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9690e+02, 9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        7.1850e+00, 6.1100e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9283e+02, 4.0300e+00]])

In [6]:
vt=VarianceThreshold(threshold=5.5)                                  #minimum energy=5.5

In [7]:
xt=vt.fit_transform(X)

In [8]:
xt[0:3,:]                                                            #columns cut down

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, 6.5200e+01, 1.0000e+00,
        2.9600e+02, 3.9690e+02, 4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, 7.8900e+01, 2.0000e+00,
        2.4200e+02, 3.9690e+02, 9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, 6.1100e+01, 2.0000e+00,
        2.4200e+02, 3.9283e+02, 4.0300e+00]])

## Principal Component Analysis

In [9]:
digits=datasets.load_digits()
X=digits.data                                                        #features
Y=digits.target                                                      #class label
                                                                     #splitting data for training and testing
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=0.2,random_state=1)

In [10]:
print(xtrain.shape)                                                  #size before PCA
print(xtest.shape)

(1437, 64)
(360, 64)


In [11]:
pca=PCA(.95)                                                         #95% accuracy to regenerate original data 

In [12]:
pca.fit(xtrain)

PCA(copy=True, iterated_power='auto', n_components=0.95, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [13]:
X_train = pca.transform(xtrain)
X_test = pca.transform(xtest)

In [14]:
print(X_train.shape)                                                  #size after PCA
print(X_test.shape)

(1437, 28)
(360, 28)


In [15]:
pca.n_components_                                                     #No. of components reduced to

28

## Feature Extraction : Vectorizing

## DictVectorizer

In [16]:
data = [{"price":1000, "rooms":4, "neighbourhood":"Pune"},
       {"price":2000, "rooms":2, "neighbourhood":"Mumbai"},
       {"price":6000, "rooms":5, "neighbourhood":"Nashik"},
       {"price":3000, "rooms":3, "neighbourhood":"Pune"}]

In [17]:
vsc=DictVectorizer(sparse=False,dtype=int)                         #DictVectorizer

In [18]:
vsc.fit_transform(data)                                            #1 if exists, 0 if not

array([[   0,    0,    1, 1000,    4],
       [   1,    0,    0, 2000,    2],
       [   0,    1,    0, 6000,    5],
       [   0,    0,    1, 3000,    3]], dtype=int32)

In [19]:
vsc.get_feature_names()                                            #column names

['neighbourhood=Mumbai',
 'neighbourhood=Nashik',
 'neighbourhood=Pune',
 'price',
 'rooms']

In [20]:
vsc=DictVectorizer(sparse=True,dtype=int)                          #handling sparse data

In [21]:
d=vsc.fit_transform(data)
print(d)                                                           #vectors

  (0, 2)	1
  (0, 3)	1000
  (0, 4)	4
  (1, 0)	1
  (1, 3)	2000
  (1, 4)	2
  (2, 1)	1
  (2, 3)	6000
  (2, 4)	5
  (3, 2)	1
  (3, 3)	3000
  (3, 4)	3


In [22]:
vsc.get_feature_names()                                            #features

['neighbourhood=Mumbai',
 'neighbourhood=Nashik',
 'neighbourhood=Pune',
 'price',
 'rooms']

## CountVectorizer

In [23]:
sample=['problem of queen','evil queen','horizon problem','evil queen']

In [24]:
vec=CountVectorizer()                                              #CountVectorizer
x=vec.fit_transform(sample)
print(x)

  (0, 4)	1
  (0, 2)	1
  (0, 3)	1
  (1, 0)	1
  (1, 4)	1
  (2, 1)	1
  (2, 3)	1
  (3, 0)	1
  (3, 4)	1


## TfidfVectorizer

In [25]:
pd.DataFrame(x.toarray(),columns=vec.get_feature_names())

evil  horizon  of  problem  queen
0     0        0   1        1      1
1     1        0   0        0      1
2     0        1   0        1      0
3     1        0   0        0      1

In [26]:
vec=TfidfVectorizer()                                         #tfidf vectorizer for text analysis:Term freq and inverse id freq
x=vec.fit_transform(sample)
print(x)

  (0, 3)	0.5534923152870045
  (0, 2)	0.7020348194149619
  (0, 4)	0.4480997313625986
  (1, 4)	0.6292275146695526
  (1, 0)	0.7772211620785797
  (2, 3)	0.6191302964899972
  (2, 1)	0.7852882757103967
  (3, 4)	0.6292275146695526
  (3, 0)	0.7772211620785797


In [27]:
pd.DataFrame(x.toarray(),columns=vec.get_feature_names())

evil   horizon        of   problem     queen
0  0.000000  0.000000  0.702035  0.553492  0.448100
1  0.777221  0.000000  0.000000  0.000000  0.629228
2  0.000000  0.785288  0.000000  0.619130  0.000000
3  0.777221  0.000000  0.000000  0.000000  0.629228